# Jekyll Configuration
theme: jekyll-theme-minimal
title: Surya Pratap Singh
description: Research Engineer at UMich
logo: assets/img/Pers_pic.png
google_analytics: G-placeholder
url_cv: https://drive.google.com/file/d/1dIJL8Cq6scokzfknjDX3FfvYRUuGklTg/view?usp=sharing
url_github: https://github.com/spsingh37
url_email: suryasin@umich.edu
url_linkedin:  https://linkedin.com/in/spsingh37
url_scholar: https://scholar.google.com/citations?user=mYGoL6IAAAAJ&hl=en
